### ISSUE TITLE
Bug - Kykinite Ore does not drop XP

### ISSUE THREAD

**Issue by Siuolplex** [Siuolthepic/Kykinite#5]
Dev Note: Most likely is due to overwriting weirdness.

Roadmap for fix puts it at 1.1.0

**Comment by kwpugh** [comment]
I think this is you are instaciating from Block instead of OreBlock.

 public static final Block KYKINITE_ORE = register("kykinite_ore", new Block(FabricBlockSettings.of(Material.METAL).hardness(4.0f).breakByTool(FabricToolTags.PICKAXES, 3).requiresTool()));

versus

 public static final Block KYKINITE_ORE = register("kykinite_ore", new OreBlock(FabricBlockSettings.of(Material.METAL).hardness(4.0f).breakByTool(FabricToolTags.PICKAXES, 3).requiresTool()));

**Comment by Siuolplex** [comment]
I thought I did on my local source code, Ill update the code here though.

Edit: Currently, its hooking into my extension of Oreblock, "SiuolOreBlock". So Ill do more debuging when I can.

**Comment by Siuolplex** [comment]
Alright uh yeah you were right. I was just very, very dumb. I had most of the block settings referring to SiuolOreBlock/KykiniteOreBlock flipped.
Kudos to you, my friend. @kwpugh 

Note to self: Read what registry items are where.
